Add formatting consistency.

diff --git a/instance-store-ami-tasks/72b-bundle-image b/instance-store-ami-tasks/72b-bundle-image
--- a/instance-store-ami-tasks/72b-bundle-image
+++ b/instance-store-ami-tasks/72b-bundle-image
@@ -1,18 +1,20 @@
 #!/bin/bash
+#
 # Bundle of instance image
 
-bundledir=${debootstrap_dir}/${volume_id}-bundle
-mkdir $bundledir
+bundledir="${debootstrap_dir}/${volume_id}-bundle"
+mkdir "${bundledir}"
 
-ami_name="$distribution-$codename-$arch-$name_suffix"
+ami_name="${distribution}-${codename}-${arch}-${name_suffix}"
 
 b_arch="${arch}"
 if [ "${arch}" = "amd64" ]
 then
-  b_arch="x86_64"
+    b_arch="x86_64"
 fi
 
-euca-bundle-image -r "${b_arch}" -i "${image_file}" -d $bundledir -p "${ami_name}"
-if [ $? -ne 0 ]; then
-  die "Unable to bundle instance image."
+euca-bundle-image -r "${b_arch}" -i "${image_file}" -d "${bundledir}" -p "${ami_name}"
+if [ $? -ne 0 ]
+then
+    die "Unable to bundle instance image."
 fi
diff --git a/instance-store-ami-tasks/72c-upload-bundle b/instance-store-ami-tasks/72c-upload-bundle
--- a/instance-store-ami-tasks/72c-upload-bundle
+++ b/instance-store-ami-tasks/72c-upload-bundle
@@ -1,7 +1,9 @@
 #!/bin/bash
+#
 # Upload instance image bundle to S3
 
 euca-upload-bundle -b "${S3_BUCKET}" -m "${bundledir}/${ami_name}.manifest.xml"
-if [ $? -ne 0 ]; then
-  die "Unable to upload image bundle to S3."
+if [ $? -ne 0 ]
+then
+    die "Unable to upload image bundle to S3."
 fi
